/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.sistema.screens;

import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Felipe Firmino
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_desktop = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        label_username = new javax.swing.JLabel();
        label_date = new javax.swing.JLabel();
        main_menu = new javax.swing.JMenuBar();
        menu_register = new javax.swing.JMenu();
        menu_register_client = new javax.swing.JMenuItem();
        menu_register_serviceorder = new javax.swing.JMenuItem();
        menu_register_users = new javax.swing.JMenuItem();
        menu_report = new javax.swing.JMenu();
        menu_report_service = new javax.swing.JMenuItem();
        menu_help = new javax.swing.JMenu();
        menu_help_about = new javax.swing.JMenuItem();
        menu_option = new javax.swing.JMenu();
        menu_option_exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema_teste");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        javax.swing.GroupLayout main_desktopLayout = new javax.swing.GroupLayout(main_desktop);
        main_desktop.setLayout(main_desktopLayout);
        main_desktopLayout.setHorizontalGroup(
            main_desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );
        main_desktopLayout.setVerticalGroup(
            main_desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistema/icons/Windows_icon.png"))); // NOI18N

        label_username.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_username.setText("User :");

        label_date.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_date.setText("Date :");

        menu_register.setText("Register");

        menu_register_client.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_SPACE, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_register_client.setText("Client");
        menu_register_client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_register_clientActionPerformed(evt);
            }
        });
        menu_register.add(menu_register_client);

        menu_register_serviceorder.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_register_serviceorder.setText("Service Order");
        menu_register_serviceorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_register_serviceorderActionPerformed(evt);
            }
        });
        menu_register.add(menu_register_serviceorder);

        menu_register_users.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_register_users.setText("Users");
        menu_register_users.setEnabled(false);
        menu_register_users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_register_usersActionPerformed(evt);
            }
        });
        menu_register.add(menu_register_users);

        main_menu.add(menu_register);

        menu_report.setText("Report");
        menu_report.setEnabled(false);

        menu_report_service.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_report_service.setText("Service Report");
        menu_report_service.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_report_serviceActionPerformed(evt);
            }
        });
        menu_report.add(menu_report_service);

        main_menu.add(menu_report);

        menu_help.setText("Help");
        menu_help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_helpActionPerformed(evt);
            }
        });

        menu_help_about.setText("About");
        menu_help_about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_help_aboutActionPerformed(evt);
            }
        });
        menu_help.add(menu_help_about);

        main_menu.add(menu_help);

        menu_option.setText("Options");

        menu_option_exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_option_exit.setText("Exit");
        menu_option_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_option_exitActionPerformed(evt);
            }
        });
        menu_option.add(menu_option_exit);

        main_menu.add(menu_option);

        setJMenuBar(main_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(main_desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_date)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_username))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(label_username)
                .addGap(48, 48, 48)
                .addComponent(label_date)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addComponent(main_desktop)
        );

        setSize(new java.awt.Dimension(850, 548));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menu_register_serviceorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_register_serviceorderActionPerformed
        // TODO add your handling code here:\
        ServiceScreen servicescreen = new ServiceScreen();
        servicescreen.setVisible(true);
        main_desktop.add(servicescreen);
    }//GEN-LAST:event_menu_register_serviceorderActionPerformed

    private void menu_report_serviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_report_serviceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_report_serviceActionPerformed

    private void menu_option_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_option_exitActionPerformed
        // TODO add your handling code here:
        int exit = JOptionPane.showConfirmDialog(null, "are you sure you want to exit?","atention",JOptionPane.YES_NO_OPTION);
        if(exit == JOptionPane.YES_OPTION ){
         System.exit(0);
        }
    }//GEN-LAST:event_menu_option_exitActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        Date date = new Date();
        DateFormat formatdate = DateFormat.getDateInstance(DateFormat.SHORT);
        label_date.setText(formatdate.format(date));
    }//GEN-LAST:event_formWindowActivated

    private void menu_helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_helpActionPerformed
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_menu_helpActionPerformed

    private void menu_help_aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_help_aboutActionPerformed
        // TODO add your handling code here:
          HelpScreen helpscreen = new HelpScreen();
          helpscreen.setVisible(true);
    }//GEN-LAST:event_menu_help_aboutActionPerformed

    private void menu_register_usersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_register_usersActionPerformed
        // TODO add your handling code here:
        UserScreen userscreen = new UserScreen();
        userscreen.setVisible(true);
        main_desktop.add(userscreen);
    }//GEN-LAST:event_menu_register_usersActionPerformed

    private void menu_register_clientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_register_clientActionPerformed
        // TODO add your handling code here:
        ClientScreen clientscreen = new ClientScreen();
        clientscreen.setVisible(true);
        main_desktop.add(clientscreen);
    }//GEN-LAST:event_menu_register_clientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel label_date;
    public static javax.swing.JLabel label_username;
    private javax.swing.JDesktopPane main_desktop;
    private javax.swing.JMenuBar main_menu;
    private javax.swing.JMenu menu_help;
    private javax.swing.JMenuItem menu_help_about;
    private javax.swing.JMenu menu_option;
    private javax.swing.JMenuItem menu_option_exit;
    private javax.swing.JMenu menu_register;
    private javax.swing.JMenuItem menu_register_client;
    private javax.swing.JMenuItem menu_register_serviceorder;
    public static javax.swing.JMenuItem menu_register_users;
    public static javax.swing.JMenu menu_report;
    private javax.swing.JMenuItem menu_report_service;
    // End of variables declaration//GEN-END:variables
}
